import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import { vetMagazines } from "../schema";
import { logStep } from "./helpers";

export async function seedVetMagazines(db: NodePgDatabase<any>, superAdmin: any) {
  console.log("📰 Seeding veterinary magazines...");

  const magazinesData = [
    {
      title: "مجلة الطب البيطري العراقي",
      description: "مجلة دورية متخصصة في الطب البيطري تصدر شهرياً",
      issueNumber: 12,
      volume: 5,
      publishedDate: new Date("2024-01-15"),
      category: "general",
      filePath: "/magazines/iraqi-vet-vol5-issue12.pdf",
      coverImage: "https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=400",
      language: "ar",
      pageCount: 120,
      tags: "طب بيطري,عام,دوري",
      isPublished: true,
      downloadCount: 543,
      rating: 4.6,
      uploadedBy: superAdmin.id,
    },
    {
      title: "نشرة الجراحة البيطرية",
      description: "نشرة شهرية متخصصة في التقنيات الجراحية الحديثة",
      issueNumber: 3,
      volume: 2,
      publishedDate: new Date("2024-03-01"),
      category: "surgery",
      filePath: "/magazines/surgery-bulletin-vol2-issue3.pdf",
      coverImage: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
      language: "ar",
      pageCount: 85,
      tags: "جراحة,تقنيات حديثة,متخصص",
      isPublished: true,
      downloadCount: 287,
      rating: 4.8,
      uploadedBy: superAdmin.id,
    },
    {
      title: "مجلة الحيوانات الأليفة",
      description: "مجلة فصلية عن رعاية وصحة الحيوانات الأليفة",
      issueNumber: 4,
      volume: 8,
      publishedDate: new Date("2023-12-01"),
      category: "pets",
      filePath: "/magazines/pets-magazine-vol8-issue4.pdf",
      coverImage: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400",
      language: "ar",
      pageCount: 95,
      tags: "حيوانات أليفة,رعاية,صحة",
      isPublished: true,
      downloadCount: 412,
      rating: 4.5,
      uploadedBy: superAdmin.id,
    },
    {
      title: "نشرة الأمراض المعدية البيطرية",
      description: "نشرة ربع سنوية عن الأمراض المعدية والوبائية",
      issueNumber: 1,
      volume: 3,
      publishedDate: new Date("2024-01-01"),
      category: "infectious_diseases",
      filePath: "/magazines/infectious-diseases-vol3-issue1.pdf",
      coverImage: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
      language: "ar",
      pageCount: 110,
      tags: "أمراض معدية,وبائيات,وقاية",
      isPublished: true,
      downloadCount: 356,
      rating: 4.7,
      uploadedBy: superAdmin.id,
    },
    {
      title: "مجلة تربية الحيوانات",
      description: "مجلة شهرية عن تربية وإدارة المزارع الحيوانية",
      issueNumber: 6,
      volume: 4,
      publishedDate: new Date("2024-02-15"),
      category: "farming",
      filePath: "/magazines/animal-husbandry-vol4-issue6.pdf",
      coverImage: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=400",
      language: "ar",
      pageCount: 78,
      tags: "تربية,إدارة مزارع,إنتاج حيواني",
      isPublished: true,
      downloadCount: 298,
      rating: 4.4,
      uploadedBy: superAdmin.id,
    },
    {
      title: "نشرة التغذية البيطرية",
      description: "نشرة متخصصة في تغذية الحيوانات والمكملات الغذائية",
      issueNumber: 8,
      volume: 6,
      publishedDate: new Date("2024-01-20"),
      category: "nutrition",
      filePath: "/magazines/nutrition-bulletin-vol6-issue8.pdf",
      coverImage: "https://images.unsplash.com/photo-1504208434309-cb69f4fe52b0?w=400",
      language: "ar",
      pageCount: 92,
      tags: "تغذية,مكملات,صحة",
      isPublished: true,
      downloadCount: 234,
      rating: 4.6,
      uploadedBy: superAdmin.id,
    },
  ];

  const createdMagazines = await db.insert(vetMagazines).values(magazinesData).returning();

  logStep(`Created ${createdMagazines.length} veterinary magazines\n`);
  return createdMagazines;
}
