import type { NodePgDatabase } from "drizzle-orm/node-postgres";
import { vetBooks } from "../schema";
import { logStep } from "./helpers";

export async function seedVetBooks(db: NodePgDatabase<any>, superAdmin: any) {
  console.log("📚 Seeding veterinary books...");

  const booksData = [
    {
      title: "أساسيات الطب البيطري",
      description: "دليل شامل للمبتدئين في الطب البيطري يغطي المفاهيم الأساسية والممارسات السريرية",
      author: "د. أحمد محمود الخطيب",
      category: "medicine",
      isbn: "978-1-234-56789-0",
      filePath: "/books/vet-basics.pdf",
      coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400",
      language: "ar",
      pageCount: 450,
      publishedYear: 2023,
      tags: "طب بيطري,تعليم,أساسيات",
      isPublished: true,
      downloadCount: 156,
      rating: 4.7,
      uploadedBy: superAdmin.id,
    },
    {
      title: "جراحة الحيوانات الصغيرة",
      description: "دليل متقدم في الجراحة البيطرية للحيوانات الأليفة مع حالات عملية وصور توضيحية",
      author: "د. فاطمة حسن النجار",
      category: "surgery",
      isbn: "978-1-234-56789-1",
      filePath: "/books/small-animal-surgery.pdf",
      coverImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=400",
      language: "ar",
      pageCount: 680,
      publishedYear: 2022,
      tags: "جراحة,حيوانات صغيرة,متقدم",
      isPublished: true,
      downloadCount: 243,
      rating: 4.9,
      uploadedBy: superAdmin.id,
    },
    {
      title: "تغذية الحيوانات الأليفة",
      description: "كتاب شامل عن التغذية السليمة للحيوانات الأليفة والمكملات الغذائية",
      author: "د. عمر سالم العراقي",
      category: "nutrition",
      isbn: "978-1-234-56789-2",
      filePath: "/books/pet-nutrition.pdf",
      coverImage: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400",
      language: "ar",
      pageCount: 320,
      publishedYear: 2023,
      tags: "تغذية,حيوانات أليفة,صحة",
      isPublished: true,
      downloadCount: 189,
      rating: 4.5,
      uploadedBy: superAdmin.id,
    },
    {
      title: "الأمراض المعدية في الحيوانات",
      description: "دراسة شاملة للأمراض المعدية وطرق الوقاية والعلاج",
      author: "د. زينب محمد البصري",
      category: "medicine",
      isbn: "978-1-234-56789-3",
      filePath: "/books/infectious-diseases.pdf",
      coverImage: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400",
      language: "ar",
      pageCount: 520,
      publishedYear: 2023,
      tags: "أمراض معدية,وقاية,علاج",
      isPublished: true,
      downloadCount: 312,
      rating: 4.8,
      uploadedBy: superAdmin.id,
    },
    {
      title: "طب الأسنان البيطري",
      description: "دليل متخصص في طب وجراحة أسنان الحيوانات",
      author: "د. حسن علي الموصلي",
      category: "dentistry",
      isbn: "978-1-234-56789-4",
      filePath: "/books/veterinary-dentistry.pdf",
      coverImage: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=400",
      language: "ar",
      pageCount: 280,
      publishedYear: 2022,
      tags: "أسنان,جراحة,متخصص",
      isPublished: true,
      downloadCount: 97,
      rating: 4.6,
      uploadedBy: superAdmin.id,
    },
    {
      title: "طب العيون البيطري",
      description: "كتاب شامل عن أمراض العيون في الحيوانات وطرق تشخيصها وعلاجها",
      author: "د. مريم خالد الكربلائي",
      category: "ophthalmology",
      isbn: "978-1-234-56789-5",
      filePath: "/books/veterinary-ophthalmology.pdf",
      coverImage: "https://images.unsplash.com/photo-1581594549595-35f6edc7b762?w=400",
      language: "ar",
      pageCount: 410,
      publishedYear: 2023,
      tags: "عيون,تشخيص,علاج",
      isPublished: true,
      downloadCount: 134,
      rating: 4.7,
      uploadedBy: superAdmin.id,
    },
    {
      title: "الطب الباطني للحيوانات",
      description: "مرجع شامل في الطب الباطني البيطري",
      author: "د. يوسف عبد الرحمن",
      category: "internal_medicine",
      isbn: "978-1-234-56789-6",
      filePath: "/books/internal-medicine.pdf",
      coverImage: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400",
      language: "ar",
      pageCount: 750,
      publishedYear: 2022,
      tags: "باطني,تشخيص,علاج شامل",
      isPublished: true,
      downloadCount: 267,
      rating: 4.9,
      uploadedBy: superAdmin.id,
    },
    {
      title: "تربية الدواجن والطيور",
      description: "دليل عملي لتربية ورعاية الدواجن والطيور الداجنة",
      author: "د. سارة أحمد الكوفي",
      category: "poultry",
      isbn: "978-1-234-56789-7",
      filePath: "/books/poultry-farming.pdf",
      coverImage: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400",
      language: "ar",
      pageCount: 380,
      publishedYear: 2023,
      tags: "دواجن,تربية,طيور",
      isPublished: true,
      downloadCount: 201,
      rating: 4.4,
      uploadedBy: superAdmin.id,
    },
  ];

  const createdBooks = await db.insert(vetBooks).values(booksData).returning();

  logStep(`Created ${createdBooks.length} veterinary books\n`);
  return createdBooks;
}
